In [1]:
import pandas as pd

df = pd.read_csv("../dataset/Loan_approval.csv")

print("Shape:", df.shape)
df.head()

Shape: (5000, 13)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,4822,Female,No,2,Graduate,Yes,48898,0,176,120.0,0.0,Urban,N
1,2364,Female,Yes,1,Not Graduate,Yes,29161,1061,172,240.0,0.0,Rural,N
2,3729,Female,No,2,Graduate,Yes,16279,2679,162,180.0,0.0,Semiurban,Y
3,624,Male,Yes,3+,Grad,No,46572,4801,-50,240.0,0.0,Urban,N
4,1074,Female,No,3+,Not Graduate,Yes,26869,14407,114,360.0,0.0,Semiurban,N

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            5000 non-null   int64
 1   Gender             4923 non-null   str
 2   Married            4934 non-null   str
 3   Dependents         4925 non-null   str
 4   Education          5000 non-null   str
 5   Self_Employed      4902 non-null   str
 6   ApplicantIncome    5000 non-null   int64
 7   CoapplicantIncome  5000 non-null   int64
 8   LoanAmount         5000 non-null   int64
 9   Loan_Amount_Term   4938 non-null   float64
 10  Credit_History     4926 non-null   float64
 11  Property_Area      4936 non-null   str
 12  Loan_Status        5000 non-null   str
dtypes: float64(2), int64(4), str(7)
memory usage: 507.9 KB

In [4]:
df.describe()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,5000.00000,5000.000000,5000.000000,5000.000000,4938.000000,4926.000000
mean,2505.14020,24802.145400,2006.445200,213.173200,235.532199,0.494925
std,1441.64834,13185.277557,3333.975591,747.150068,122.680260,0.565573
min,1.00000,3955.000000,0.000000,-50.000000,120.000000,-1.000000
25%,1254.75000,15537.000000,0.000000,115.000000,180.000000,0.000000
50%,2508.50000,21840.000000,0.000000,148.000000,240.000000,0.000000
75%,3752.25000,30762.500000,2911.500000,184.000000,360.000000,1.000000
max,5000.00000,113002.000000,37830.000000,9999.000000,999.000000,2.000000

In [5]:
df.isnull().sum()

Loan_ID               0
Gender               77
Married              66
Dependents           75
Education             0
Self_Employed        98
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     62
Credit_History       74
Property_Area        64
Loan_Status           0
dtype: int64